sudo: required

language: go
go:
  - "1.9"

services:
      - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - "echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

# script:
#     - cd contrib && contrib/ci.sh

after_success:
    - if [ ! -s "$TRAVIS_TAG" ] ; then 
        echo "Time to tag images as $TRAVIS_TAG and push remote"
      fi
