provider:
  name: faas
  gateway: http://localhost:8080

functions:
  gh-push:
    lang: go
    handler: ./gh-push
    image: alexellis2/gh-push:0.0.1
    environment:
      Http_X_Github_Event: push
      read_timeout: 5
      write_timeout: 5
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml

  git-tar:
    lang: Dockerfile
    handler: ./git-tar
    image: alexellis2/of-git-tar:0.2.1
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      read_debug: true

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: alexellis2/of-buildshiprun:0.0.1
    environment:
      read_timeout: 300
      write_timeout: 300
      default_memory_limit: 30m
      write_debug: true
      read_debug: true

  list-functions:
    lang: go
    handler: ./list-functions
    image: alexellis2/list-functions:0.1
    environment:
      write_debug: true
      read_debug: true

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: alexellis2/garbage-collect:0.1
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30
      write_timeout: 30

  git-event:
    lang: go
    handler: ./git-event
    image: alexellis2/git-event:0.1
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml
