provider:
  name: faas
  gateway: http://147.75.44.133:8080

functions:
  gh-push:
    lang: go
    handler: ./gh-push
    image: alexellis2/gh-push
    environment:
      Http_X_Github_Event: push
  git-tar:
    lang: Dockerfile
    handler: ./git-tar
    image: alexellis2/of-git-tar:0.1