provider:
  name: faas
  gateway: http://147.75.44.133:8080

functions:
  gh-push:
    lang: go
    handler: ./gh-push
    image: alexellis2/gh-push
    environment:
      Http_X_Github_Event: push
      read_timeout: 5
      write_timeout: 5

  git-tar:
    lang: Dockerfile
    handler: ./git-tar
    image: alexellis2/of-git-tar:0.2
    environment:
      read_timeout: 120
      write_timeout: 120
